name: Abdul Jeter
markdown: kramdown
plugins:
  - jekyll-seo-tag
title: Abduls Website
description: A site all about me, Abdul Jeter
author: Abdul Aziz Jeter
social:
  name: Abdul Jeter
  links:
    - https://www.twitter.com/Onejeter
    - https://www.facebook.com/bibleyj
    - https://www.instagram.com/spooky.dul
    - https://www.github.com/abdul-j
url: "https://www.abdul-j.github.io"
plugins:
  - jekyll-sitemap
